#define FORCE_NKRO

#define DYNAMIC_MACRO_DELAY 50

// #define PERMISSIVE_HOLD
#define TAPPING_TERM 200
#define QUICK_TAP_TERM 150

#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_COUNT 10
#define COMBO_TERM 24

#undef POINTING_DEVICE_ENABLE

#undef FP_AUDIO_MOUSE_BUTTONS
#undef FP_AUDIO_CUT_COPY_PASTE
#undef FP_AUDIO_SAVE

#define PLACEHOLDER_SAFE_RANGE FP_SAFE_RANGE

/* Mouse stuff
#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL    80
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_WHEEL_DELTA
#define MOUSEKEY_WHEEL_DELTA    1
#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED    8
#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX    0

#undef FP_POINTING_DEFAULT_DPI
#define FP_POINTING_DEFAULT_DPI 1
#undef FP_POINTING_SNIPING_DPI
#define FP_POINTING_SNIPING_DPI 5
#undef FP_POINTING_SCROLLING_DPI
#define FP_POINTING_SCROLLING_DPI 0
#undef FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY 
#define FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY 20
*/