MOUSEKEY_ENABLE = no
KEY_LOCK_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
TAP_DANCE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = yes
COMBO_ENABLE = yes
SEND_STRING_ENABLE = yes
ENCODER_ENABLE = yes
AUDIO_ENABLE = no
TRI_LAYER_ENABLE = no
REPEAT_KEY_ENABLE = no
CONSOLE_ENABLE = no

SRC += oneshot.c
SRC += repeat_key.c
SRC += xword.c